Add VMware workstation based RackHD + InfraSIM integration in howto c…
InfraSIM/docs pull request #21
Opened 2017-01-16 03:51 UTC by XiaowenJiang

1. Modify BMC binding use case in configuration chapter.
2. Add RackHD+InfraSIM practice instruction in howto chapter.

2017-01-16 05:25 UTC, fub2 reviewed
It should require operations to allow promiscuous mode and virtualization nesting. ESXi part highlights this. Is there any workstation related instruct ructions being added?

2017-01-16 06:52 UTC, XiaowenJiang commented
@fub2 There is no vswitch/port group promisc mode need to be set in VMWare workstation.
I just added additional instruction to remind user of VT-d flag and promisc mode for nics.

2017-01-18 06:19 UTC, turtle-fly requested changes

2017-01-18 06:19 UTC, turtle-fly commented on docs/how_to.rst
> +#. Start RackHD service and InfraSIM service.
Introduce hyperlink to RackHD quick start and InfraSIM quick start.

2017-01-18 06:19 UTC, turtle-fly commented on docs/how_to.rst
> +    * Modify yaml file to add BMC binding and change qemu network interface to bridge mode::
Yaml file default location

2017-01-18 06:19 UTC, turtle-fly commented on docs/how_to.rst
> +    B. In ``/etc/network/interfaces``, configure the ``CONTROL`` network interface to static::
``CONTROL`` to ``<CONTROL ifname>``

Add a hint for user to check ifname.

2017-01-18 06:19 UTC, turtle-fly commented on docs/how_to.rst
> +    B. Modify ``/etc/network/interfaces`` for the ``BMC`` and ``CONTROL`` networks::
Hint to check ifname

2017-01-18 06:19 UTC, turtle-fly commented on docs/how_to.rst
> +#. Create a Custom network(name it ``VMnet2`` here) in VMWare workstation with configuration below:
Emphasize it's `host-only` and explain something

2017-01-18 06:19 UTC, turtle-fly commented on docs/how_to.rst
> +#. Enable VT-d in BIOS on Physical Server as in chapter 11.1.
Add internal hyperlink, \`text <page#mark>\`_

2017-01-20 07:29 UTC, XiaowenJiang commented
@turtle-fly Modify docs as requests. Please help me review the changes

2017-01-20 08:31 UTC, turtle-fly approved these changes

2017-01-20 08:31 UTC, merged